version: "3.8"
volumes:
  db:
    driver: local
networks:
  app-network:
    driver: bridge
services:
  php-fpm:
    image: php:7.1-fpm-alpine
    container_name: php
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - app-network
    depends_on:
      - composer
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
  db:
    image: postgres:13.1-alpine
    container_name: db
    tty: true
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - app-network
  composer:
    image: composer:2.0.8
    container_name: composer
    command: [ "composer", "install" ]
    volumes:
      - ./:/app
    networks:
      - app-network